package Arith;


/**
* arith/_MultiplicationStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arith.idl
* viernes 27 de septiembre de 2013 07:09:01 AM CDT
*/

public class _MultiplicationStub extends org.omg.CORBA.portable.ObjectImpl implements Arith.Multiplication
{

  public void multiply (double x, double y, org.omg.CORBA.DoubleHolder z)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiply", true);
                $out.write_double (x);
                $out.write_double (y);
                $in = _invoke ($out);
                z.value = $in.read_double ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                multiply (x, y, z        );
            } finally {
                _releaseReply ($in);
            }
  } // multiply

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:arith/Multiplication:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MultiplicationStub
