package Arith;

/**
* arith/MultiplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arith.idl
* viernes 27 de septiembre de 2013 07:09:01 AM CDT
*/

public final class MultiplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public Arith.Multiplication value = null;

  public MultiplicationHolder ()
  {
  }

  public MultiplicationHolder (Arith.Multiplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Arith.MultiplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Arith.MultiplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Arith.MultiplicationHelper.type ();
  }

}
