package Arith;


/**
* arith/MultiplicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arith.idl
* viernes 27 de septiembre de 2013 07:09:01 AM CDT
*/

public interface MultiplicationOperations 
{
  void multiply (double x, double y, org.omg.CORBA.DoubleHolder z);
} // interface MultiplicationOperations
