package Arith;


/**
* arith/Multiplication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from arith.idl
* viernes 27 de septiembre de 2013 07:09:01 AM CDT
*/

public interface Multiplication extends MultiplicationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Multiplication
