package Operaciones;


/**
* Operaciones/SumaNumeros.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* miércoles 12 de octubre de 2016 06:07:02 PM CDT
*/

public interface SumaNumeros extends SumaNumerosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SumaNumeros
