package Operaciones;


/**
* Operaciones/SumaNumerosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* miércoles 12 de octubre de 2016 06:07:02 PM CDT
*/

public interface SumaNumerosOperations 
{
  int suma (int x, int y);
} // interface SumaNumerosOperations
