package Palabras;

/**
* Palabras/CuentaPalabrasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CuentaPalabras.idl
* viernes 14 de octubre de 2016 09:29:44 AM CDT
*/

public final class CuentaPalabrasHolder implements org.omg.CORBA.portable.Streamable
{
  public Palabras.CuentaPalabras value = null;

  public CuentaPalabrasHolder ()
  {
  }

  public CuentaPalabrasHolder (Palabras.CuentaPalabras initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Palabras.CuentaPalabrasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Palabras.CuentaPalabrasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Palabras.CuentaPalabrasHelper.type ();
  }

}
