package Palabras;


/**
* Palabras/CuentaPalabras.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CuentaPalabras.idl
* viernes 14 de octubre de 2016 09:29:44 AM CDT
*/

public interface CuentaPalabras extends CuentaPalabrasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CuentaPalabras
