package Palabras;


/**
* Palabras/CuentaPalabrasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CuentaPalabras.idl
* viernes 14 de octubre de 2016 09:29:44 AM CDT
*/

public interface CuentaPalabrasOperations 
{
  int cuentaPalabras (String palabra);
} // interface CuentaPalabrasOperations
