package Ejemplo;


/**
* Ejemplo/_ConsultorioStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Consultorio.idl
* viernes 21 de octubre de 2016 09:35:16 AM CDT
*/

public class _ConsultorioStub extends org.omg.CORBA.portable.ObjectImpl implements Ejemplo.Consultorio
{

  public String agendarConsulta (String doctor, String horario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("agendarConsulta", true);
                $out.write_string (doctor);
                $out.write_string (horario);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return agendarConsulta (doctor, horario        );
            } finally {
                _releaseReply ($in);
            }
  } // agendarConsulta

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ejemplo/Consultorio:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ConsultorioStub
