package Ejemplo;


/**
* Ejemplo/ConsultorioPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Consultorio.idl
* viernes 21 de octubre de 2016 09:35:16 AM CDT
*/

public abstract class ConsultorioPOA extends org.omg.PortableServer.Servant
 implements Ejemplo.ConsultorioOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("agendarConsulta", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Ejemplo/Consultorio/agendarConsulta
       {
         String doctor = in.read_string ();
         String horario = in.read_string ();
         String $result = null;
         $result = this.agendarConsulta (doctor, horario);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ejemplo/Consultorio:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Consultorio _this() 
  {
    return ConsultorioHelper.narrow(
    super._this_object());
  }

  public Consultorio _this(org.omg.CORBA.ORB orb) 
  {
    return ConsultorioHelper.narrow(
    super._this_object(orb));
  }


} // class ConsultorioPOA
