package Ejemplo;


/**
* Ejemplo/Consultorio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Consultorio.idl
* viernes 21 de octubre de 2016 09:35:16 AM CDT
*/

public interface Consultorio extends ConsultorioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Consultorio
