package Ejemplo;

/**
* Ejemplo/ConsultorioHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Consultorio.idl
* viernes 21 de octubre de 2016 09:35:16 AM CDT
*/

public final class ConsultorioHolder implements org.omg.CORBA.portable.Streamable
{
  public Ejemplo.Consultorio value = null;

  public ConsultorioHolder ()
  {
  }

  public ConsultorioHolder (Ejemplo.Consultorio initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ejemplo.ConsultorioHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ejemplo.ConsultorioHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ejemplo.ConsultorioHelper.type ();
  }

}
