package Arith;


/**
* Arith/OperacionesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathOperaciones.idl
* jueves 13 de octubre de 2016 08:41:43 PM CDT
*/

abstract public class OperacionesHelper
{
  private static String  _id = "IDL:Arith/Operaciones:1.0";

  public static void insert (org.omg.CORBA.Any a, Arith.Operaciones that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Arith.Operaciones extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Arith.OperacionesHelper.id (), "Operaciones");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Arith.Operaciones read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OperacionesStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Arith.Operaciones value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Arith.Operaciones narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Arith.Operaciones)
      return (Arith.Operaciones)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Arith._OperacionesStub stub = new Arith._OperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Arith.Operaciones unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Arith.Operaciones)
      return (Arith.Operaciones)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Arith._OperacionesStub stub = new Arith._OperacionesStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
