package Arith;


/**
* Arith/Operaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathOperaciones.idl
* jueves 13 de octubre de 2016 08:41:43 PM CDT
*/

public interface Operaciones extends OperacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Operaciones
