package Arith;


/**
* Arith/OperacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathOperaciones.idl
* jueves 13 de octubre de 2016 08:41:43 PM CDT
*/

public interface OperacionesOperations 
{
  double suma (double x, double y);
  double resta (double x, double y);
  double multiplica (double x, double y);
  double divide (double x, double y);
} // interface OperacionesOperations
