package Arith;

/**
* Arith/OperacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MathOperaciones.idl
* jueves 13 de octubre de 2016 08:41:43 PM CDT
*/

public final class OperacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public Arith.Operaciones value = null;

  public OperacionesHolder ()
  {
  }

  public OperacionesHolder (Arith.Operaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Arith.OperacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Arith.OperacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Arith.OperacionesHelper.type ();
  }

}
